server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_system
    username: blockcode
    password: Password@123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: filesystem:../db/migrations
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: info

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}
      access-token-ttl-seconds: ${JWT_TTL_SECONDS:1800}
  auth:
    google:
      client-id: ${APP_AUTH_GOOGLE_CLIENT_ID:}
      client-secret: ${APP_AUTH_GOOGLE_CLIENT_SECRET:}
      redirect-uri: ${APP_AUTH_GOOGLE_REDIRECT_URI:}
      storefront-base-url: ${APP_STOREFRONT_BASE_URL:}
